In [1]:
import h5py
import numpy as np
import torch

In [2]:
b = {"var1": torch.tensor([0.1, 0.2])}
batch = torch.tensor([0, 1])
for k in b:
    a = torch.Tensor()
    for i in batch.long():
        a = torch.cat((a, torch.tensor([b[k][i]])))
    print(a, a.shape)

tensor([0.1000, 0.2000]) torch.Size([2])


In [2]:
x = [1, 2, 3]
y = [4, 5, 6]
X, Y = np.meshgrid(x, y)
print(X, X.ravel())
print(Y, Y.ravel())

[[1 2 3]
 [1 2 3]
 [1 2 3]] [1 2 3 1 2 3 1 2 3]
[[4 4 4]
 [5 5 5]
 [6 6 6]] [4 4 4 5 5 5 6 6 6]


In [3]:
X = X.ravel()
Y = Y.ravel()
coordinates = np.concatenate((X[..., None], Y[..., None]), axis=-1)
print(coordinates)

[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]
 [1 6]
 [2 6]
 [3 6]]
